/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.EldenRing.isaac.gui;

import org.example.EldenRing.isaac.events.FightEventListner;
import org.example.EldenRing.isaac.manager.GameManager;
import org.example.EldenRing.isaac.models.characters.Character;
import org.example.EldenRing.isaac.models.characters.Fightable;
import org.example.EldenRing.isaac.models.characters.MainCharacter;
import org.example.EldenRing.isaac.models.characters.interactions.Interaction;
import org.example.EldenRing.isaac.models.characters.interactions.Skill;

import javax.swing.*;

/**
 *
 * @author trapa
 */
public class MainCharacterOptions extends javax.swing.JPanel implements FightEventListner {

    /**
     * Creates new form MainCharacterOptions
     */
    public MainCharacterOptions() {
        initComponents();
        GameManager.getInstance().subscribeFightListner(this);
    }
    public MainCharacterOptions(MainCharacter character) {
        initComponents();
        this.setBackground(java.awt.Color.GREEN);
        GameManager.getInstance().subscribeFightListner(this);
        //iter through the character and add the buttons
        for (Skill skill : character.getSkills()) {
            this.jPanelInteractionsContainer.add(new InteractionPanel(skill));

        }
    }
    public JComponent addAll(JComponent ... components){
        for (JComponent component : components) {
            this.add(component);
        }
        return this;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelActualHealthAndMaxHealth = new javax.swing.JLabel();
        jPanelInteractionsContainer = new javax.swing.JPanel();

        jLabelActualHealthAndMaxHealth.setText("jLabel1");

        jPanelInteractionsContainer.setLayout(new java.awt.GridLayout(2, 2, 15, 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelActualHealthAndMaxHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInteractionsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelActualHealthAndMaxHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(jPanelInteractionsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelActualHealthAndMaxHealth;
    private javax.swing.JPanel jPanelInteractionsContainer;

    @Override
    public void startTurn(Character character, Boolean isally) {
        if (isally){
            this.jLabelActualHealthAndMaxHealth.setText(character.getCurrentHealth()+"/"+character.getMaxHealth());
            this.jPanelInteractionsContainer.removeAll();
            this.jPanelInteractionsContainer.revalidate();
            this.jPanelInteractionsContainer.repaint();
        }
    }


    // End of variables declaration//GEN-END:variables
}
