/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.EldenRing.isaac.gui;

import org.example.EldenRing.isaac.events.FightEventListner;
import org.example.EldenRing.isaac.manager.GameManager;
import org.example.EldenRing.isaac.models.characters.Character;
import org.example.EldenRing.isaac.models.characters.Fightable;
import org.example.EldenRing.isaac.models.characters.MainCharacter;
import org.example.EldenRing.isaac.models.characters.Target;
import org.example.EldenRing.isaac.models.characters.interactions.Interaction;
import org.example.EldenRing.isaac.models.characters.interactions.Skill;

import javax.swing.*;

/**
 *
 * @author trapa
 */
public class MainCharacterOptions extends javax.swing.JPanel implements FightEventListner {

    /**
     * Creates new form MainCharacterOptions
     */
    public MainCharacterOptions() {
        initComponents();
        GameManager.getInstance().subscribeFightListner(this);
    }
    public MainCharacterOptions(MainCharacter character) {
        initComponents();
        this.setBackground(java.awt.Color.GREEN);
        GameManager.getInstance().subscribeFightListner(this);
        //iter through the character and add the buttons
        for (Skill skill : character.getSkills()) {
            this.jPanelInteractionsContainer.add(new InteractionPanel(skill));

        }
    }
    @Override
    public void startTurn(Character character, Boolean isally) {

    }

    @Override
    public void setColor(Skill.TargetType targetType) {

    }

    @Override
    public void setTarget(Target target) {

    }

    @Override
    public void resetTarget() {

    }

    public JComponent addAll(JComponent ... components){
        for (JComponent component : components) {
            this.add(component);
        }
        return this;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInteractionsContainer = new javax.swing.JPanel();

        jPanelInteractionsContainer.setLayout(new java.awt.GridLayout(4, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInteractionsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInteractionsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelInteractionsContainer;
    // End of variables declaration//GEN-END:variables
}
