/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.EldenRing.isaac.gui;



import org.example.EldenRing.isaac.events.GameEventListner;
import org.example.EldenRing.isaac.factory.FightingRoomFactory;
import org.example.EldenRing.isaac.factory.NormalPrizeRoomFactory;
import org.example.EldenRing.isaac.factory.StarterRoomFactory;
import org.example.EldenRing.isaac.manager.GameManager;
import org.example.EldenRing.isaac.models.characters.type.MainCharacter;
import org.example.EldenRing.isaac.piano.Piano;
import org.example.EldenRing.isaac.RoomCoordinates;

import java.awt.*;
import java.util.List;

/**
 * @author trapa
 */
public class MainFrame extends javax.swing.JFrame implements GameEventListner {
    private static int piano = Piano.getNumero();
    private List<MainCharacter> character;
    public static int getPiano() {
        return piano;
    }

    public List<MainCharacter> getCharacter() {
        return character;
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {  
        GameManager.getInstance().subscribeGameListner(this);
        this.character=GameManager.getInstance().getCharacter();
        initComponents();
        this.setMinimumSize(new Dimension(900, 900));
        setLocationRelativeTo(null);
        this.jLabelCharacterName.setText(this.character.get(0).getName());
        this.jLabelHealth.setText(this.character.get(0).getCurrentHealth()+" / "+ this.character.get(0).getMaxHealth());
        GameManager.getInstance().startGame();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabelCharacterName = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(50, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(30, 0));
        jLabelHealth = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));

        jPanelContainer.setBackground(new java.awt.Color(255, 153, 0));
        jPanelContainer.setLayout(new java.awt.GridLayout(15, 15, 1, 1));

        jToolBar1.setBackground(new java.awt.Color(204, 0, 0));
        jToolBar1.setRollover(true);
        jToolBar1.add(filler1);

        jLabelCharacterName.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabelCharacterName.setText("jLabel1");
        jToolBar1.add(jLabelCharacterName);
        jToolBar1.add(filler3);
        jToolBar1.add(filler2);

        jLabelHealth.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabelHealth.setText("jLabel1");
        jToolBar1.add(jLabelHealth);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;

    public void setCharacter(List<MainCharacter> character) {
        this.character = character;
    }

    @Override
    public void newGame(Piano piano) {
        int[][] roomMap = piano.getRoomMap();
        for (int i = 0; i < 15; i++) {
            for (int j = 0; j < 15; j++) {
                if (roomMap[i][j] == 2) {
                    this.jPanelContainer.add(new RoomPanel(new RoomCoordinates(i, j), true,new StarterRoomFactory().createRoom(new RoomCoordinates(i,j)),null));
                } else if (roomMap[i][j] == 1) {
                    double random = Math.random();
                    if (random <0.35) {
                        this.jPanelContainer.add(new RoomPanel(new RoomCoordinates(i, j), false,new NormalPrizeRoomFactory().createRoom(new RoomCoordinates(i,j)),null));
                    }
                    else {
                        this.jPanelContainer.add(new RoomPanel(new RoomCoordinates(i, j), false,new FightingRoomFactory().createRoom(new RoomCoordinates(i,j)),null));

                    }


                } else {
                    this.jPanelContainer.add(new NoRoomPanel());
                }
            }
        }
    }

    @Override
    public void move(RoomCoordinates roomCoordinates) {

    }

    @Override
    public void enteredRoom() {

    }

    @Override
    public void selectCharacter(List<MainCharacter> character) {
        this.character = character;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabelCharacterName;
    private javax.swing.JLabel jLabelHealth;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
